### ISSUE TITLE
Comment of the code

### ISSUE THREAD

**Issue by me-shaon** [Sayef/99-Text-Compressor#1]
Please convert the comments to 'English', so anyone from anywhere can understand it. As it is a global platform of developers, you don't know who is reading your code. :)

**Comment by sayef** [comment]
Wrote these almost 3.5 years ago. Hardly can remember which one is for what. :p But obviously will have a try. Thanks :)

**Comment by sayef** [comment]
Comments translated to English. :)

**Comment by me-shaon** [comment]
Good job. (y) Change this issues status from 'open' to 'resolved'.

**Comment by sayef** [comment]
Thanks again :)
